BEGIN;

CREATE TABLE IF NOT EXISTS "adminCredentials" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "username" varchar(80) NOT NULL,
  "passwordHash" varchar(255) NOT NULL,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "adminCredentials_userId_unique" UNIQUE ("userId"),
  CONSTRAINT "adminCredentials_username_unique" UNIQUE ("username")
);

CREATE TABLE IF NOT EXISTS "appTextSettings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "appName" varchar(100) NOT NULL DEFAULT 'Meu Fiado',
  "slogan" varchar(240) NOT NULL DEFAULT 'Acompanhando de perto suas metas todos dias.',
  "welcomeTitle" varchar(180) NOT NULL DEFAULT 'Acompanhe suas metas de recebimento',
  "welcomeDescription" varchar(600) NOT NULL DEFAULT 'Tenha uma visão clara das metas, indicadores e resultados da sua filial.',
  "overviewTitle" varchar(120) NOT NULL DEFAULT 'Visão Geral',
  "overviewDescription" varchar(240) NOT NULL DEFAULT 'Confira o desempenho e a projeção do seu recebimento.',
  "utilitiesTitle" varchar(120) NOT NULL DEFAULT 'Utilidades',
  "utilitiesDescription" varchar(240) NOT NULL DEFAULT 'Arquivos, relatórios e ferramentas para apoiar sua rotina.',
  "subscriptionTitle" varchar(120) NOT NULL DEFAULT 'Plano',
  "subscriptionDescription" varchar(240) NOT NULL DEFAULT 'Gerencie seu acesso e envie o comprovante após o pagamento.',
  "navOverview" varchar(80) NOT NULL DEFAULT 'Visão Geral',
  "navBranches" varchar(80) NOT NULL DEFAULT 'Filiais',
  "navHistory" varchar(80) NOT NULL DEFAULT 'Históricos',
  "navUtilities" varchar(80) NOT NULL DEFAULT 'Utilidades',
  "navChat" varchar(80) NOT NULL DEFAULT 'Chat',
  "navSettings" varchar(80) NOT NULL DEFAULT 'Ajustes',
  "navPreferences" varchar(80) NOT NULL DEFAULT 'Preferências',
  "navAccount" varchar(80) NOT NULL DEFAULT 'Conta',
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "branchMetrics" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "branchId" integer NOT NULL,
  "creditGoal" double precision NOT NULL DEFAULT 0,
  "challengeGoal" double precision NOT NULL DEFAULT 0,
  "currentOverdue" double precision NOT NULL DEFAULT 0,
  "monthlyLoss" double precision NOT NULL DEFAULT 0,
  "lossSalesPercent" double precision NOT NULL DEFAULT 0,
  "lostGoal" double precision NOT NULL DEFAULT 0,
  "lostReceived" double precision NOT NULL DEFAULT 0,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "portfolioTotal" double precision NOT NULL DEFAULT 0,
  "monthOpening" double precision NOT NULL DEFAULT 0,
  "dayOpening" double precision NOT NULL DEFAULT 0,
  "workingDaysTotal" integer NOT NULL DEFAULT 0,
  "workingDaysElapsed" integer NOT NULL DEFAULT 0,
  "ticketWorkingDaysRemaining" integer NOT NULL DEFAULT 0,
  "fiadoAtDay15" boolean NOT NULL DEFAULT false,
  "workingDaysMode" varchar(12) NOT NULL DEFAULT 'automatic',
  "manualHolidayDatesJson" text NOT NULL,
  "countToday" boolean NOT NULL DEFAULT true,
  "includeSaturday" boolean NOT NULL DEFAULT true,
  "includeSunday" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "branchMetrics_branchId_unique" UNIQUE ("branchId")
);

CREATE TABLE IF NOT EXISTS "branches" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(120) NOT NULL,
  "code" varchar(32) DEFAULT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "regional" varchar(120) DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "branches_name_unique" UNIQUE ("name"),
  CONSTRAINT "branches_code_unique" UNIQUE ("code")
);

CREATE TABLE IF NOT EXISTS "chatMessages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "senderUserId" integer NOT NULL,
  "recipientUserId" integer DEFAULT NULL,
  "body" varchar(1200) NOT NULL,
  "expiresAt" timestamp NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "supportTopic" varchar(120) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "chatReadStates" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "lastReadMessageId" integer NOT NULL DEFAULT 0,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "chatReadStates_userId_unique" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS "matrixImportSources" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "source" text NOT NULL,
  "importedAt" timestamp NOT NULL,
  "receivedRows" integer NOT NULL DEFAULT 0,
  "validRows" integer NOT NULL DEFAULT 0,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "matrixImportSources_source_unique" UNIQUE ("source")
);

CREATE TABLE IF NOT EXISTS "matrixMetrics" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "branchId" integer NOT NULL,
  "creditGoal" double precision NOT NULL DEFAULT 0,
  "challengeGoal" double precision NOT NULL DEFAULT 0,
  "received" double precision NOT NULL DEFAULT 0,
  "monthlyLoss" double precision NOT NULL DEFAULT 0,
  "lossSalesPercent" double precision NOT NULL DEFAULT 0,
  "lostGoal" double precision NOT NULL DEFAULT 0,
  "lostReceived" double precision NOT NULL DEFAULT 0,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "delinquencyPercent" double precision NOT NULL DEFAULT 0,
  "creditEffectivenessPercent" double precision NOT NULL DEFAULT 0,
  "challengeEffectivenessPercent" double precision NOT NULL DEFAULT 0,
  "ticketGoal" double precision NOT NULL DEFAULT 0,
  "ticketPercent" double precision NOT NULL DEFAULT 0,
  "ticketBonus" double precision NOT NULL DEFAULT 0,
  "lossEffectivenessPercent" double precision NOT NULL DEFAULT 0,
  "amountReceivable" double precision NOT NULL DEFAULT 0,
  "overdueOpening" double precision NOT NULL DEFAULT 0,
  "portfolioTotal" double precision NOT NULL DEFAULT 0,
  "receiptForecast" double precision NOT NULL DEFAULT 0,
  "closingForecast" double precision NOT NULL DEFAULT 0,
  "closingForecastPercent" double precision NOT NULL DEFAULT 0,
  "accumulatedLossGoal" double precision NOT NULL DEFAULT 0,
  "accumulatedLossReceived" double precision NOT NULL DEFAULT 0,
  "accumulatedLossBalance" double precision NOT NULL DEFAULT 0,
  "previousDayGoal" double precision NOT NULL DEFAULT 0,
  "dailyReceived" double precision NOT NULL DEFAULT 0,
  "previousDayDifference" double precision NOT NULL DEFAULT 0,
  "accumulatedDifference" double precision NOT NULL DEFAULT 0,
  "redesignedDailyGoal" double precision NOT NULL DEFAULT 0,
  "challengeDailyReceivedJson" text DEFAULT NULL,
  "sales" double precision NOT NULL DEFAULT 0,
  "receiptDailyJson" text DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "matrixMetrics_branchId_unique" UNIQUE ("branchId")
);

CREATE TABLE IF NOT EXISTS "mercadoPagoSubscriptionPayments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mercadoPagoSubscriptionId" integer NOT NULL,
  "userId" integer NOT NULL,
  "authorizedPaymentId" varchar(120) NOT NULL,
  "paymentId" varchar(120) DEFAULT NULL,
  "paymentStatus" varchar(48) NOT NULL,
  "amount" double precision NOT NULL,
  "paidAt" timestamp NULL DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "mercado_pago_authorized_payment_unique" UNIQUE ("authorizedPaymentId"),
  CONSTRAINT "mercado_pago_payment_unique" UNIQUE ("paymentId")
);

CREATE TABLE IF NOT EXISTS "mercadoPagoSubscriptions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "externalReference" varchar(120) NOT NULL,
  "preapprovalId" varchar(120) DEFAULT NULL,
  "checkoutUrl" varchar(2048) DEFAULT NULL,
  "providerStatus" varchar(48) NOT NULL DEFAULT 'pending',
  "amount" double precision NOT NULL,
  "currencyId" varchar(3) NOT NULL DEFAULT 'BRL',
  "nextPaymentDate" timestamp NULL DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "mercadoPagoSubscriptions_userId_unique" UNIQUE ("userId"),
  CONSTRAINT "mercado_pago_subscriptions_reference_unique" UNIQUE ("externalReference"),
  CONSTRAINT "mercado_pago_subscriptions_preapproval_unique" UNIQUE ("preapprovalId")
);

CREATE TABLE IF NOT EXISTS "metricSettings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "portfolioTotal" double precision NOT NULL DEFAULT 0,
  "monthOpening" double precision NOT NULL DEFAULT 0,
  "dayOpening" double precision NOT NULL DEFAULT 0,
  "currentOverdue" double precision NOT NULL DEFAULT 0,
  "creditGoal" double precision NOT NULL DEFAULT 0,
  "challengeGoal" double precision NOT NULL DEFAULT 0,
  "lostGoal" double precision NOT NULL DEFAULT 0,
  "lostReceived" double precision NOT NULL DEFAULT 0,
  "workingDaysTotal" integer NOT NULL DEFAULT 0,
  "workingDaysElapsed" integer NOT NULL DEFAULT 0,
  "fiadoAtDay15" boolean NOT NULL DEFAULT false,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ticketWorkingDaysRemaining" integer NOT NULL DEFAULT 0,
  "workingDaysMode" varchar(12) NOT NULL DEFAULT 'automatic',
  "manualHolidayDatesJson" text NOT NULL,
  "countToday" boolean NOT NULL DEFAULT true,
  "includeSaturday" boolean NOT NULL DEFAULT true,
  "includeSunday" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "metricSettings_userId_unique" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS "receiptHistoryEntries" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "branchId" integer NOT NULL,
  "entryDate" date NOT NULL,
  "receivedAmount" double precision NOT NULL,
  "createdByUserId" integer DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "receipt_history_branch_date_unique" UNIQUE ("branchId","entryDate")
);

CREATE TABLE IF NOT EXISTS "romaneioActivities" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "romaneioId" integer NOT NULL,
  "romaneioActivitySigner" text NOT NULL,
  "managerName" varchar(160) NOT NULL,
  "signatureStyle" varchar(32) NOT NULL,
  "occurredAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "romaneioItems" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "romaneioId" integer NOT NULL,
  "position" integer NOT NULL,
  "productCode" varchar(80) DEFAULT NULL,
  "productName" varchar(255) NOT NULL,
  "unit" varchar(24) NOT NULL DEFAULT 'UN',
  "requestedQuantity" double precision NOT NULL DEFAULT 0,
  "approvedQuantity" double precision NOT NULL DEFAULT 0,
  "deliveredQuantity" double precision NOT NULL DEFAULT 0,
  "notes" varchar(600) DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "romaneio_items_position_unique" UNIQUE ("romaneioId","position")
);

CREATE TABLE IF NOT EXISTS "romaneioParties" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(180) NOT NULL,
  "normalizedName" varchar(180) NOT NULL,
  "branch" varchar(120) NOT NULL DEFAULT '',
  "normalizedBranch" varchar(120) NOT NULL DEFAULT '',
  "address" varchar(255) DEFAULT NULL,
  "neighborhood" varchar(120) DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "preferredSignatureStyle" varchar(32) DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "romaneio_parties_name_branch_unique" UNIQUE ("normalizedName","normalizedBranch")
);

CREATE TABLE IF NOT EXISTS "romaneioProducts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(80) NOT NULL,
  "normalizedCode" varchar(80) NOT NULL,
  "description" varchar(255) NOT NULL,
  "unit" varchar(24) NOT NULL DEFAULT 'UN',
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "romaneio_products_code_unique" UNIQUE ("normalizedCode")
);

CREATE TABLE IF NOT EXISTS "romaneios" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "createdByUserId" integer NOT NULL,
  "shareToken" varchar(96) NOT NULL,
  "romaneioStatus" text NOT NULL DEFAULT 'draft',
  "documentNumber" varchar(80) DEFAULT NULL,
  "transferDate" date NOT NULL,
  "originName" varchar(180) NOT NULL,
  "originBranch" varchar(120) DEFAULT NULL,
  "originAddress" varchar(255) DEFAULT NULL,
  "originNeighborhood" varchar(120) DEFAULT NULL,
  "originCity" varchar(120) DEFAULT NULL,
  "originState" varchar(2) DEFAULT NULL,
  "originManagerName" varchar(160) NOT NULL,
  "originSignatureUrl" varchar(2048) DEFAULT NULL,
  "originSignedAt" timestamp NULL DEFAULT NULL,
  "destinationName" varchar(180) NOT NULL,
  "destinationBranch" varchar(120) DEFAULT NULL,
  "destinationAddress" varchar(255) DEFAULT NULL,
  "destinationNeighborhood" varchar(120) DEFAULT NULL,
  "destinationCity" varchar(120) DEFAULT NULL,
  "destinationState" varchar(2) DEFAULT NULL,
  "destinationManagerName" varchar(160) NOT NULL,
  "destinationSignatureUrl" varchar(2048) DEFAULT NULL,
  "destinationSignedAt" timestamp NULL DEFAULT NULL,
  "notes" text DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pdfUrl" varchar(2048) DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "romaneios_share_token_unique" UNIQUE ("shareToken")
);

CREATE TABLE IF NOT EXISTS "subscriptionProofs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "proofUrl" varchar(2048) NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "reviewNote" varchar(600) DEFAULT NULL,
  "reviewedByUserId" integer DEFAULT NULL,
  "reviewedAt" timestamp NULL DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "subscriptionSettings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "monthlyPrice" double precision NOT NULL DEFAULT 0,
  "pixKey" varchar(255) NOT NULL DEFAULT '',
  "branchesPlan" text NOT NULL DEFAULT 'pro',
  "historyPlan" text NOT NULL DEFAULT 'pro',
  "utilitiesPlan" text NOT NULL DEFAULT 'pro',
  "chatPlan" text NOT NULL DEFAULT 'pro',
  "updatedByUserId" integer DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pixReceiverName" varchar(25) NOT NULL DEFAULT 'MEU FIADO',
  "pixReceiverBank" varchar(80) NOT NULL DEFAULT '',
  "pixCopyPaste" varchar(2048) NOT NULL DEFAULT '',
  "pixQrCodeUrl" varchar(2048) NOT NULL DEFAULT '',
  "promotionPrice" double precision NOT NULL DEFAULT 0,
  "promotionOriginalPrice" double precision NOT NULL DEFAULT 0,
  "planInfoTitle" varchar(180) NOT NULL DEFAULT 'Plano PRO do Meu Fiado',
  "planInfoDescription" varchar(800) NOT NULL DEFAULT 'Tenha acesso aos recursos avançados e acompanhe sua assinatura por aqui.',
  "planInfoBackground" varchar(24) NOT NULL DEFAULT 'sky',
  "planInfoCtaEnabled" boolean NOT NULL DEFAULT false,
  "planInfoCtaLabel" varchar(80) NOT NULL DEFAULT '',
  "planInfoCtaUrl" varchar(2048) NOT NULL DEFAULT '',
  "overviewPlan" text NOT NULL DEFAULT 'free',
  "matrixPlan" text NOT NULL DEFAULT 'pro',
  "metricsPlan" text NOT NULL DEFAULT 'free',
  "appearancePlan" text NOT NULL DEFAULT 'free',
  "helpPlan" text NOT NULL DEFAULT 'free',
  "updatesPlan" text NOT NULL DEFAULT 'free',
  "promotionBadge" varchar(80) NOT NULL DEFAULT 'Oferta especial',
  "promotionTitle" varchar(180) NOT NULL DEFAULT 'Plano PRO em oferta',
  "promotionDescription" varchar(800) NOT NULL DEFAULT 'Aproveite o valor promocional para liberar todos os recursos PRO.',
  "promotionBackground" varchar(24) NOT NULL DEFAULT 'emerald',
  "promotionCtaLabel" varchar(80) NOT NULL DEFAULT 'Assinar PRO com Mercado Pago',
  "subscriberGoalMinimum" integer NOT NULL DEFAULT 0,
  "subscriberGoalCurrent" integer NOT NULL DEFAULT 0,
  "subscriberGoalContext" varchar(800) NOT NULL DEFAULT '',
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "supportConversations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "requesterUserId" integer NOT NULL,
  "adminUserId" integer NOT NULL,
  "topic" varchar(120) NOT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "support_conversations_pair_unique" UNIQUE ("requesterUserId","adminUserId")
);

CREATE TABLE IF NOT EXISTS "updateNotes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(180) NOT NULL,
  "description" text NOT NULL,
  "category" varchar(80) NOT NULL DEFAULT 'Geral',
  "isVisible" boolean NOT NULL DEFAULT true,
  "createdByUserId" integer DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "updateReadStates" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "lastReadUpdateId" integer NOT NULL DEFAULT 0,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "updateReadStates_userId_unique" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS "userCredentials" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "passwordHash" varchar(255) NOT NULL,
  "mustChangePassword" boolean NOT NULL DEFAULT true,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "userCredentials_userId_unique" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS "userProfiles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer DEFAULT NULL,
  "email" varchar(320) NOT NULL,
  "fullName" varchar(160) NOT NULL,
  "branchId" integer DEFAULT NULL,
  "phone" varchar(32) DEFAULT NULL,
  "instagram" varchar(120) DEFAULT NULL,
  "operatorType" text NOT NULL DEFAULT 'leader',
  "isActive" boolean NOT NULL DEFAULT true,
  "isOnVacation" boolean NOT NULL DEFAULT false,
  "showLostGoal" boolean NOT NULL DEFAULT false,
  "colorMode" text NOT NULL DEFAULT 'light',
  "colorPalette" text NOT NULL DEFAULT 'ocean',
  "profileComplete" boolean NOT NULL DEFAULT false,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "avatarUrl" varchar(2048) DEFAULT NULL,
  "messageNotificationsEnabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id"),
  CONSTRAINT "userProfiles_userId_unique" UNIQUE ("userId"),
  CONSTRAINT "profiles_email_unique" UNIQUE ("email"),
  CONSTRAINT "profiles_branch_operator_unique" UNIQUE ("branchId","operatorType")
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "openId" varchar(64) NOT NULL,
  "name" text DEFAULT NULL,
  "email" varchar(320) DEFAULT NULL,
  "loginMethod" varchar(64) DEFAULT NULL,
  "role" text NOT NULL DEFAULT 'user',
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSignedIn" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "plan" text NOT NULL DEFAULT 'free',
  "proExpiresAt" timestamp NULL DEFAULT NULL,
  "supportAvailability" text NOT NULL DEFAULT 'available',
  PRIMARY KEY ("id"),
  CONSTRAINT "users_openId_unique" UNIQUE ("openId")
);

CREATE TABLE IF NOT EXISTS "utilityDownloads" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(180) NOT NULL,
  "fileType" varchar(32) NOT NULL,
  "externalUrl" varchar(2048) NOT NULL,
  "isPinned" boolean NOT NULL DEFAULT false,
  "isVisible" boolean NOT NULL DEFAULT true,
  "createdByUserId" integer DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "utilityReports" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(180) NOT NULL,
  "description" text NOT NULL,
  "isVisible" boolean NOT NULL DEFAULT true,
  "createdByUserId" integer DEFAULT NULL,
  "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "chatMessages_senderUserId_users_id_fk" ON "chatMessages" ("senderUserId");

CREATE INDEX IF NOT EXISTS "chatMessages_recipientUserId_users_id_fk" ON "chatMessages" ("recipientUserId");

CREATE INDEX IF NOT EXISTS "chat_messages_expiry_idx" ON "chatMessages" ("expiresAt");

CREATE INDEX IF NOT EXISTS "chat_messages_private_idx" ON "chatMessages" ("senderUserId","recipientUserId","createdAt");

CREATE INDEX IF NOT EXISTS "mpsp_subscription_fk" ON "mercadoPagoSubscriptionPayments" ("mercadoPagoSubscriptionId");

CREATE INDEX IF NOT EXISTS "mpsp_user_fk" ON "mercadoPagoSubscriptionPayments" ("userId");

CREATE INDEX IF NOT EXISTS "mercado_pago_subscription_payments_user_created_idx" ON "mercadoPagoSubscriptionPayments" ("userId","createdAt");

CREATE INDEX IF NOT EXISTS "receiptHistoryEntries_createdByUserId_users_id_fk" ON "receiptHistoryEntries" ("createdByUserId");

CREATE INDEX IF NOT EXISTS "receipt_history_branch_date_idx" ON "receiptHistoryEntries" ("branchId","entryDate");

CREATE INDEX IF NOT EXISTS "romaneioActivities_romaneioId_romaneios_id_fk" ON "romaneioActivities" ("romaneioId");

CREATE INDEX IF NOT EXISTS "romaneio_activities_document_time_idx" ON "romaneioActivities" ("romaneioId","occurredAt");

CREATE INDEX IF NOT EXISTS "romaneio_items_document_idx" ON "romaneioItems" ("romaneioId");

CREATE INDEX IF NOT EXISTS "romaneio_parties_recent_idx" ON "romaneioParties" ("updatedAt");

CREATE INDEX IF NOT EXISTS "romaneio_products_recent_idx" ON "romaneioProducts" ("updatedAt");

CREATE INDEX IF NOT EXISTS "romaneios_createdByUserId_users_id_fk" ON "romaneios" ("createdByUserId");

CREATE INDEX IF NOT EXISTS "romaneios_owner_updated_idx" ON "romaneios" ("createdByUserId","updatedAt");

CREATE INDEX IF NOT EXISTS "romaneios_status_updated_idx" ON "romaneios" ("romaneioStatus","updatedAt");

CREATE INDEX IF NOT EXISTS "subscriptionProofs_userId_users_id_fk" ON "subscriptionProofs" ("userId");

CREATE INDEX IF NOT EXISTS "subscriptionProofs_reviewedByUserId_users_id_fk" ON "subscriptionProofs" ("reviewedByUserId");

CREATE INDEX IF NOT EXISTS "subscription_proofs_user_status_idx" ON "subscriptionProofs" ("userId","status","createdAt");

CREATE INDEX IF NOT EXISTS "subscriptionSettings_updatedByUserId_users_id_fk" ON "subscriptionSettings" ("updatedByUserId");

CREATE INDEX IF NOT EXISTS "supportConversations_adminUserId_users_id_fk" ON "supportConversations" ("adminUserId");

CREATE INDEX IF NOT EXISTS "support_conversations_admin_idx" ON "supportConversations" ("adminUserId","updatedAt");

CREATE INDEX IF NOT EXISTS "updateNotes_createdByUserId_users_id_fk" ON "updateNotes" ("createdByUserId");

CREATE INDEX IF NOT EXISTS "update_notes_visibility_idx" ON "updateNotes" ("isVisible","createdAt");

CREATE INDEX IF NOT EXISTS "userProfiles_branchId_branches_id_fk" ON "userProfiles" ("branchId");

CREATE INDEX IF NOT EXISTS "utilityDownloads_createdByUserId_users_id_fk" ON "utilityDownloads" ("createdByUserId");

CREATE INDEX IF NOT EXISTS "utility_downloads_visibility_idx" ON "utilityDownloads" ("isVisible","isPinned","updatedAt");

CREATE INDEX IF NOT EXISTS "utilityReports_createdByUserId_users_id_fk" ON "utilityReports" ("createdByUserId");

CREATE INDEX IF NOT EXISTS "utility_reports_visibility_idx" ON "utilityReports" ("isVisible","updatedAt");

ALTER TABLE "adminCredentials" ADD CONSTRAINT "adminCredentials_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "branchMetrics" ADD CONSTRAINT "branchMetrics_branchId_branches_id_fk" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "chatMessages" ADD CONSTRAINT "chatMessages_senderUserId_users_id_fk" FOREIGN KEY ("senderUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "chatMessages" ADD CONSTRAINT "chatMessages_recipientUserId_users_id_fk" FOREIGN KEY ("recipientUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "chatReadStates" ADD CONSTRAINT "chatReadStates_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "matrixMetrics" ADD CONSTRAINT "matrixMetrics_branchId_branches_id_fk" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "mercadoPagoSubscriptionPayments" ADD CONSTRAINT "mpsp_subscription_fk" FOREIGN KEY ("mercadoPagoSubscriptionId") REFERENCES "mercadoPagoSubscriptions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "mercadoPagoSubscriptionPayments" ADD CONSTRAINT "mpsp_user_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "mercadoPagoSubscriptions" ADD CONSTRAINT "mps_user_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "metricSettings" ADD CONSTRAINT "metricSettings_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "receiptHistoryEntries" ADD CONSTRAINT "receiptHistoryEntries_branchId_branches_id_fk" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "receiptHistoryEntries" ADD CONSTRAINT "receiptHistoryEntries_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "romaneioActivities" ADD CONSTRAINT "romaneioActivities_romaneioId_romaneios_id_fk" FOREIGN KEY ("romaneioId") REFERENCES "romaneios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "romaneioItems" ADD CONSTRAINT "romaneioItems_romaneioId_romaneios_id_fk" FOREIGN KEY ("romaneioId") REFERENCES "romaneios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "romaneios" ADD CONSTRAINT "romaneios_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "subscriptionProofs" ADD CONSTRAINT "subscriptionProofs_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "subscriptionProofs" ADD CONSTRAINT "subscriptionProofs_reviewedByUserId_users_id_fk" FOREIGN KEY ("reviewedByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "subscriptionSettings" ADD CONSTRAINT "subscriptionSettings_updatedByUserId_users_id_fk" FOREIGN KEY ("updatedByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "supportConversations" ADD CONSTRAINT "supportConversations_requesterUserId_users_id_fk" FOREIGN KEY ("requesterUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "supportConversations" ADD CONSTRAINT "supportConversations_adminUserId_users_id_fk" FOREIGN KEY ("adminUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "updateNotes" ADD CONSTRAINT "updateNotes_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "updateReadStates" ADD CONSTRAINT "updateReadStates_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "userCredentials" ADD CONSTRAINT "userCredentials_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "userProfiles" ADD CONSTRAINT "userProfiles_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "userProfiles" ADD CONSTRAINT "userProfiles_branchId_branches_id_fk" FOREIGN KEY ("branchId") REFERENCES "branches" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "utilityDownloads" ADD CONSTRAINT "utilityDownloads_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "utilityReports" ADD CONSTRAINT "utilityReports_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT;

