ALTER TABLE "adminCredentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "appTextSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "branchMetrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "branches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chatMessages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chatReadStates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "matrixImportSources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "matrixMetrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mercadoPagoSubscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mercadoPagoSubscriptionPayments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "metricSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "receiptHistoryEntries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "romaneios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "romaneioActivities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "romaneioItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "romaneioParties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "romaneioProducts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptionProofs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptionSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "supportConversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "updateNotes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "updateReadStates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "userCredentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "userProfiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "utilityDownloads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "utilityReports" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "adminCredentials_service_role_all" ON "adminCredentials" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "appTextSettings_service_role_all" ON "appTextSettings" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "branchMetrics_service_role_all" ON "branchMetrics" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "branches_service_role_all" ON "branches" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "chatMessages_service_role_all" ON "chatMessages" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "chatReadStates_service_role_all" ON "chatReadStates" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "matrixImportSources_service_role_all" ON "matrixImportSources" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "matrixMetrics_service_role_all" ON "matrixMetrics" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "mercadoPagoSubscriptions_service_role_all" ON "mercadoPagoSubscriptions" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "mercadoPagoSubscriptionPayments_service_role_all" ON "mercadoPagoSubscriptionPayments" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "metricSettings_service_role_all" ON "metricSettings" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "receiptHistoryEntries_service_role_all" ON "receiptHistoryEntries" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "romaneios_service_role_all" ON "romaneios" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "romaneioActivities_service_role_all" ON "romaneioActivities" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "romaneioItems_service_role_all" ON "romaneioItems" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "romaneioParties_service_role_all" ON "romaneioParties" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "romaneioProducts_service_role_all" ON "romaneioProducts" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "subscriptionProofs_service_role_all" ON "subscriptionProofs" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "subscriptionSettings_service_role_all" ON "subscriptionSettings" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "supportConversations_service_role_all" ON "supportConversations" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "updateNotes_service_role_all" ON "updateNotes" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "updateReadStates_service_role_all" ON "updateReadStates" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "userCredentials_service_role_all" ON "userCredentials" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "userProfiles_service_role_all" ON "userProfiles" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "users_service_role_all" ON "users" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "utilityDownloads_service_role_all" ON "utilityDownloads" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "utilityReports_service_role_all" ON "utilityReports" FOR ALL TO service_role USING (true) WITH CHECK (true);
