import { Button } from "@/components/ui/button";
import { ArrowRight, BarChart3, Building2, CheckCircle2, ShieldCheck, Target } from "lucide-react";
import React from "react";
import { Link } from "wouter";

export default function Welcome() {
  return <main className="relative min-h-screen overflow-hidden bg-[radial-gradient(circle_at_15%_10%,color-mix(in_oklab,var(--primary)_15%,transparent),transparent_35%),radial-gradient(circle_at_85%_85%,color-mix(in_oklab,var(--chart-2)_16%,transparent),transparent_38%)] px-5 py-7 text-foreground sm:px-10 lg:px-16">
    <div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/25"><BarChart3 className="h-5 w-5" /></div><div><p className="font-black tracking-tight">Meu Fiado</p><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-muted-foreground">Painel de metas</p></div></div><div className="flex items-center gap-1"><Link href="/entrar" className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">Entrar</Link><Link href="/cadastro" className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">Cadastrar</Link><Link href="/admin/login" className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">Admin</Link></div></div>
    <section className="mx-auto grid max-w-6xl items-center gap-12 py-20 lg:min-h-[calc(100vh-80px)] lg:grid-cols-[1.05fr_.95fr] lg:py-0"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary"><CheckCircle2 className="h-3.5 w-3.5" />Metas claras. Decisões diárias.</p><h1 className="max-w-xl text-4xl font-black leading-[1.04] tracking-[-0.055em] sm:text-6xl">Acompanhando de suas metas <span className="text-primary">todos dias.</span></h1><p className="mt-6 max-w-lg text-base leading-relaxed text-muted-foreground sm:text-lg">Acompanhe Meta Fiado, Desafio, Ticket e Perdido em um só lugar, com projeções diárias e premiações por função.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 rounded-xl px-6 text-sm font-extrabold shadow-lg shadow-primary/25"><Link href="/entrar">Entrar no painel <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" size="lg" className="h-12 rounded-xl px-6 text-sm font-extrabold"><Link href="/cadastro">Cadastrar</Link></Button><div className="flex items-center px-3 text-xs font-semibold text-muted-foreground"><ShieldCheck className="mr-2 h-4 w-4 text-emerald-500" />Acesso protegido pelo Google</div></div></div>
    <div className="relative mx-auto w-full max-w-md rounded-[2rem] border border-border/70 bg-card p-5 shadow-2xl shadow-primary/10"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-muted-foreground">Projeção de hoje</p><p className="mt-1 text-3xl font-black tracking-tight">R$ 18.420</p></div><div className="rounded-2xl bg-emerald-500/10 px-3 py-2 text-right text-emerald-600"><p className="text-lg font-black">96,4%</p><p className="text-[10px] font-bold">Meta Fiado</p></div></div><div className="mt-6 h-2.5 overflow-hidden rounded-full bg-muted"><div className="h-full w-[91%] rounded-full bg-gradient-to-r from-primary to-chart-2" /></div><div className="mt-7 grid grid-cols-3 gap-3">{[[Target,"Metas"],[Building2,"Filiais"],[BarChart3,"Ritmo diário"]].map(([Icon,label]) => { const Visual = Icon as typeof Target; return <div key={String(label)} className="rounded-2xl bg-muted/60 p-3"><Visual className="h-4 w-4 text-primary" /><p className="mt-3 text-[11px] font-bold">{String(label)}</p></div>})}</div><div className="mt-5 rounded-2xl border border-primary/15 bg-primary/5 p-4"><p className="text-xs font-bold">Próxima faixa: 98%</p><p className="mt-1 text-[11px] text-muted-foreground">Veja o valor que falta e o ritmo ideal por dia útil.</p></div></div></section>
  </main>;
}
