from pathlib import Path
p = Path('/home/ubuntu/painel-recebimentos/client/src/pages/Dashboard.tsx')
s = p.read_text()
s = s.replace('  const ticketValid = type === "leader" && ticket.status === "achieved";', '  const showTicketGoal = profile.showTicketGoal ?? true;\n  const showPossibleRewards = profile.showPossibleRewards ?? true;\n  const ticketValid = type === "leader" && ticket.status === "achieved";', 1)
s = s.replace('tiers={fiadoTiers} daysTotal=', 'tiers={fiadoTiers} showPossibleRewards={showPossibleRewards} daysTotal=', 1)
s = s.replace('tiers={challengeTiers} daysTotal=', 'tiers={challengeTiers} showPossibleRewards={showPossibleRewards} daysTotal=', 1)
s = s.replace('{type === "leader" ? <TicketStatus ticket={ticket} /> : <AssistantNotice />}', '{showTicketGoal ? type === "leader" ? <TicketStatus ticket={ticket} dailyReceived={receipts.today} showPossibleRewards={showPossibleRewards} /> : <AssistantNotice /> : null}', 1)
s = s.replace('{canShowForecast && <><ReceiptProjectionCard', '{canShowForecast && <><ReceiptProjectionCard', 1)
s = s.replace('<QuickStat icon={ArrowUpRight} label="Meta 80%" value={currency(ticket.target)} note="" />\n        <QuickStat icon={ArrowUpRight} label="Falta para 80%" value={currency(ticket.remaining)} note={ticket.afterDay15 ? "Prazo encerrado" : "Saldo até o dia 15"} />\n        <QuickStat icon={Clock3} label="Por dia até o dia 15" value={currency(ticket.dailyNeeded)} note={`${metrics.ticketWorkingDaysRemaining} dias úteis restantes`} />', '{showTicketGoal && <><QuickStat icon={ArrowUpRight} label="Meta 80%" value={currency(ticket.target)} note="" />\n        <QuickStat icon={ArrowUpRight} label="Falta para 80%" value={currency(ticket.remaining)} note={ticket.afterDay15 ? "Prazo encerrado" : "Saldo até o dia 15"} />\n        <QuickStat icon={Clock3} label="Por dia até o dia 15" value={currency(ticket.dailyNeeded)} note={`${metrics.ticketWorkingDaysRemaining} dias úteis restantes`} /></>}', 1)
s = s.replace('function TicketStatus({ ticket }: { ticket: ReturnType<typeof ticketGoalState> }) {', 'function TicketStatus({ ticket, dailyReceived, showPossibleRewards }: { ticket: ReturnType<typeof ticketGoalState>; dailyReceived: number; showPossibleRewards: boolean }) {', 1)
s = s.replace('<div><p className="text-xl font-black">{currency(100)}</p><p className="mt-1 text-[11px] text-muted-foreground">Premiação possível</p></div><div><p className="text-sm font-black">{currency(ticket.target)}</p>', '<div><p className="text-xl font-black">{currency(100)}</p><p className="mt-1 text-[11px] text-muted-foreground">Premiação possível</p></div><div><p className="text-sm font-black">{currency(ticket.target)}</p>', 1)
s = s.replace('<div className="text-left sm:text-right"><p className="text-sm font-black">{currency(ticket.remaining)}</p><p className="mt-1 text-[11px] text-muted-foreground">Falta para atingir</p></div>', '<div><p className="text-sm font-black">{currency(dailyReceived)}</p><p className="mt-1 text-[11px] text-muted-foreground">Recebido hoje</p></div><div className="text-left sm:text-right"><p className="text-sm font-black">{currency(ticket.remaining)}</p><p className="mt-1 text-[11px] text-muted-foreground">Falta para atingir</p></div>', 1)
s = s.replace('<div><p className="text-xl font-black">{currency(100)}</p><p className="mt-1 text-[11px] text-muted-foreground">Premiação possível</p></div>', '{showPossibleRewards && <div><p className="text-xl font-black">{currency(100)}</p><p className="mt-1 text-[11px] text-muted-foreground">Premiação possível</p></div>}', 1)
p.write_text(s)

p = Path('/home/ubuntu/painel-recebimentos/client/src/components/GoalCard.tsx')
s = p.read_text()
s = s.replace('  accent?: "primary" | "violet";\n};', '  accent?: "primary" | "violet";\n  showPossibleRewards?: boolean;\n};', 1)
s = s.replace('projectionTargets }: GoalCardProps)', 'projectionTargets, showPossibleRewards = true }: GoalCardProps)', 1)
s = s.replace('<p className="mt-0.5 text-[11px] text-muted-foreground">Premiação: {currency(accumulated)} de {currency(total)}</p>', '<p className="mt-0.5 text-[11px] text-muted-foreground">Premiação: {currency(accumulated)}{showPossibleRewards ? ` de ${currency(total)}` : ""}</p>', 1)
p.write_text(s)
print('dashboard ticket visibility patched')
